### ISSUE TITLE
findLimeSDR.py example leaves board undiscoverable

### ISSUE THREAD

**Issue by bvacaliuc** [myriadrf/pyLMS7002M#1]
**(this is observed on MacOS)**

When running the [findLimeSDR](https://github.com/myriadrf/pyLMS7002M/blob/master/examples/basic/findLimeSDR.py) example, the LimeSDR board is left in an undiscoverable state:

```
(pyLMS7002m) basic $ python findLimeSDR.py 
Searching for LimeSDR...

LimeSDR info:
FW_VER           : 3
DEV_TYPE         : 14
LMS_PROTOCOL_VER : 1
HW_VER           : 4
EXP_BOARD        : 1

LMS7002M info:
VER              : 7
REV              : 1
MASK             : 1
(pyLMS7002m) basic $ python findLimeSDR.py 
Searching for LimeSDR...
LimeSDR not found
```
Is there a required close procedure?  Even skipping the ```limeSDR.LMS7002_Reset()``` does not make the device discoverable again.  Only a physical disconnect restores connectivity.

Using [LimeSuiteGUI](https://wiki.myriadrf.org/LimeSDR-USB_Quick_Test) when the device is in this state gives the following output:
```
(pyLMS7002m) basic $ LimeSuiteGUI
LMS7002M values cache at /Users/xxx/.limesuite/LMS7002M_cache_values.db
libusb: warning [darwin_transfer_status] transfer error: device not responding (value = 0xe00002ed)

########################################################
##   !!!  Warning: gateware version mismatch  !!!
## Expected gateware version 2, revision 6
## But found version 0, revision 0
## Follow the FW and FPGA upgrade instructions:
## http://wiki.myriadrf.org/Lime_Suite#Flashing_images
## Or run update on the command line: LimeUtil --update
########################################################

libusb: error [submit_bulk_transfer] bulk transfer failed (dir = Out): pipe is stalled (code = 0xe000404f)
libusb: error [submit_bulk_transfer] bulk transfer failed (dir = Out): pipe is stalled (code = 0xe000404f)
libusb: error [submit_bulk_transfer] bulk transfer failed (dir = Out): pipe is stalled (code = 0xe000404f)
libusb: error [submit_bulk_transfer] bulk transfer failed (dir = Out): pipe is stalled (code = 0xe000404f)
libusb: error [submit_bulk_transfer] bulk transfer failed (dir = Out): pipe is stalled (code = 0xe000404f)
libusb: error [submit_bulk_transfer] bulk transfer failed (dir = Out): pipe is stalled (code = 0xe000404f)
(pyLMS7002m) basic $ 
```
Using the LimeSuiteGUI only does not exhibit this behavior no matter how many times it is closed:
**(disconnect/reconnect LimeSDR)**
```
(pyLMS7002m) basic $ LimeSuiteGUI
LMS7002M values cache at /Users/xxx/.limesuite/LMS7002M_cache_values.db
Estimated reference clock 30.7197 MHz
Selected reference clock 30.720 MHz
aluminum:Lime_Suite 6ov$ LimeSuiteGUI
LMS7002M values cache at /Users/xxx/.limesuite/LMS7002M_cache_values.db
Estimated reference clock 30.7197 MHz
Selected reference clock 30.720 MHz
(pyLMS7002m) basic $
```

**Comment by bvacaliuc** [comment]
Here is a one-line test:
```
(pyLMS7002m) $ python -c "from pyLMS7002M import * ; limeSDR = LimeSDR()"
(pyLMS7002m) $ python -c "from pyLMS7002M import * ; limeSDR = LimeSDR()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/pyLMS7002M/LimeSDR.py", line 123, in __init__
  File "build/bdist.macosx-10.6-x86_64/egg/pyLMS7002M/LMS7002.py", line 62, in __init__
  File "build/bdist.macosx-10.6-x86_64/egg/pyLMS7002M/weakproxy.py", line 43, in __call__
  File "build/bdist.macosx-10.6-x86_64/egg/pyLMS7002M/LimeSDR.py", line 356, in LMS7002_Read
  File "build/bdist.macosx-10.6-x86_64/egg/pyLMS7002M/LimeSDR.py", line 231, in sendCommand
  File "build/bdist.macosx-10.6-x86_64/egg/pyLMS7002M/boardUSB.py", line 72, in bulkWrite
  File "/Users/xxx/anaconda/envs/pyLMS7002m/lib/python2.7/site-packages/usb/core.py", line 948, in write
    self.__get_timeout(timeout)
  File "/Users/xxx/anaconda/envs/pyLMS7002m/lib/python2.7/site-packages/usb/backend/libusb1.py", line 824, in bulk_write
    timeout)
  File "/Users/xxx/anaconda/envs/pyLMS7002m/lib/python2.7/site-packages/usb/backend/libusb1.py", line 920, in __write
    _check(retval)
  File "/Users/xxx/anaconda/envs/pyLMS7002m/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error
```
In case you need to know, I setup my python environment using these [instructions](https://github.com/bvacaliuc/pyrasdr#macos)
