### ISSUE TITLE
No module named 'LMS7002_EVB' running   python measureVNA.py

### ISSUE THREAD

**Issue by mariocannistra** [myriadrf/pyLMS7002M#3]
I'm getting this error message when running  `python measureVNA.py`  :

```
Traceback (most recent call last):
  File "measureVNA.py", line 5, in <module>
    from pyLMS7002M import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylms7002m-1.2.0-py3.6.egg\pyLMS7002M\__init__.py", line 2, in <module>
ModuleNotFoundError: No module named 'LMS7002_EVB'
```

I'm working on Windows 8.1 Pro and using Python 3.6.1 installed by Anaconda 4.4.0 (64-bit).

I've installed pyLMS7002M from sources using `python setup.py install` and this is the output of the command where I don't see errors:

```
running install
running bdist_egg
running egg_info
writing pyLMS7002M.egg-info\PKG-INFO
writing dependency_links to pyLMS7002M.egg-info\dependency_links.txt
writing requirements to pyLMS7002M.egg-info\requires.txt
writing top-level names to pyLMS7002M.egg-info\top_level.txt
reading manifest file 'pyLMS7002M.egg-info\SOURCES.txt'
writing manifest file 'pyLMS7002M.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\ADF4002.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\boardUSB.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LimeSDR.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LimeSDR_FPGA.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_AFE.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_base.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_BIAS.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_calibration.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_CDS.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_CGEN.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_CHIP.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_DCCAL.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_EVB.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_GFIR.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_GFIR1.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_GFIR2.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_GFIR3.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_IO.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_LimeLight.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_mSPI.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_NCO.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_RBB.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_regDataStructs.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_REGDESC.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_REGDESC_MR3.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_RFE.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_RxTSP.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_SX.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_TBB.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_TRF.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_TxTSP.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\LMS7002_XBUF.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\QSpark.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\QSpark_FPGA.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\Si5351.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\weakproxy.py -> build\bdist.win-amd64\egg\pyLMS7002M
copying build\lib\pyLMS7002M\__init__.py -> build\bdist.win-amd64\egg\pyLMS7002M
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\ADF4002.py to ADF4002.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\boardUSB.py to boardUSB.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LimeSDR.py to LimeSDR.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LimeSDR_FPGA.py to LimeSDR_FPGA.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002.py to LMS7002.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_AFE.py to LMS7002_AFE.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_base.py to LMS7002_base.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_BIAS.py to LMS7002_BIAS.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_calibration.py to LMS7002_calibration.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_CDS.py to LMS7002_CDS.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_CGEN.py to LMS7002_CGEN.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_CHIP.py to LMS7002_CHIP.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_DCCAL.py to LMS7002_DCCAL.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_EVB.py to LMS7002_EVB.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_GFIR.py to LMS7002_GFIR.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_GFIR1.py to LMS7002_GFIR1.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_GFIR2.py to LMS7002_GFIR2.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_GFIR3.py to LMS7002_GFIR3.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_IO.py to LMS7002_IO.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_LimeLight.py to LMS7002_LimeLight.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_mSPI.py to LMS7002_mSPI.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_NCO.py to LMS7002_NCO.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_RBB.py to LMS7002_RBB.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_regDataStructs.py to LMS7002_regDataStructs.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_REGDESC.py to LMS7002_REGDESC.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_REGDESC_MR3.py to LMS7002_REGDESC_MR3.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_RFE.py to LMS7002_RFE.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_RxTSP.py to LMS7002_RxTSP.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_SX.py to LMS7002_SX.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_TBB.py to LMS7002_TBB.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_TRF.py to LMS7002_TRF.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_TxTSP.py to LMS7002_TxTSP.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\LMS7002_XBUF.py to LMS7002_XBUF.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\QSpark.py to QSpark.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\QSpark_FPGA.py to QSpark_FPGA.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\Si5351.py to Si5351.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\weakproxy.py to weakproxy.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pyLMS7002M\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying pyLMS7002M.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying pyLMS7002M.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pyLMS7002M.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pyLMS7002M.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying pyLMS7002M.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\pyLMS7002M-1.2.0-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pyLMS7002M-1.2.0-py3.6.egg
Removing c:\programdata\anaconda3\lib\site-packages\pyLMS7002M-1.2.0-py3.6.egg
Copying pyLMS7002M-1.2.0-py3.6.egg to c:\programdata\anaconda3\lib\site-packages
pyLMS7002M 1.2.0 is already the active version in easy-install.pth

Installed c:\programdata\anaconda3\lib\site-packages\pylms7002m-1.2.0-py3.6.egg
Processing dependencies for pyLMS7002M==1.2.0
Searching for pyusb==1.0.0
Best match: pyusb 1.0.0
Processing pyusb-1.0.0-py3.6.egg
pyusb 1.0.0 is already the active version in easy-install.pth

Using c:\programdata\anaconda3\lib\site-packages\pyusb-1.0.0-py3.6.egg
Searching for pyserial==3.3
Best match: pyserial 3.3
Processing pyserial-3.3-py3.6.egg
pyserial 3.3 is already the active version in easy-install.pth
Installing miniterm.py script to C:\ProgramData\Anaconda3\Scripts

Using c:\programdata\anaconda3\lib\site-packages\pyserial-3.3-py3.6.egg
Finished processing dependencies for pyLMS7002M==1.2.0
```

**Comment by 9600** [comment]
The library is written for Python 2.7 and you need to install this instead of 3.6.
